### ISSUE TITLE
Inline Drag&Drop broken on Django Unfold

### ISSUE THREAD

**Issue by raayu83** [jrief/django-admin-sortable2#403] opened 2024-08-02 08:18 UTC
Hello,

when using this app together with Django Unfold, the Inline sorting function is broken:
If you drag an entry, only the title part is dragged, the dropdown part is ignored and stays in the old place.

I'm not that deep into JavaScript, but if you can give me some hints what I need to look into I'd be willing to give it a try to fix this issue.

In case it is important, my Inline Class signature is like this:

`class MyInline(unfold.admin.TabularInline, adminsortable2.admin.SortableStackedInline)`

Tabularinline needs to be first, otherwise the styling is broken.

**Comment by jrief** [comment] 2024-08-02 09:37
Duplicate of #398

**Closed by jrief** 2024-08-02 09:37 UTC
