### ISSUE TITLE
Updated ordering values not getting saved

### ISSUE THREAD

**Issue by paddymul** [jrief/django-admin-sortable2#160] opened 2017-07-16 20:13 UTC
I have an application that uses django-admin-sortable2.  At some point the reordering functionality was working correctly.  After a series of changes to my application, the reordering functionality is no longer working.  Due to migrations and other changes it is not easy to do a git bisect to find the last working state.

As it is, the reordering renders, and inlines are draggable.  When I drag an inline to a new position then click save, the database isn't updated.

I have put a pdb.set_trace on the inline model's save() function and I can see that no new value for the ordering parameter are being passed in.

I'm not sure how to debug further.  

I am currently running
firefox, django 1.11.3, grapelli, django-admin-sortable2 0.6.13

I was seeing the same non working functionality when running against django 10.5, by disabling grapilli, and on django-admin-sortable2 0.6.4

What can I do to provide you with more debugging information? I realize that this isn't a particularly specific bug report.

Thanks

**Comment by timmyomahony** [comment] 2017-07-20 13:25
I'm also noticing this. Same for inlines. The javascript reordering works but when I save it just reverts to the previous ordering.

**Comment by jrief** [comment] 2017-07-21 09:21
The field you're using to keep the ordering information is non-unique. Therefore it might be possible that due to some unfinished commits some values might be duplicated. First, please check in the database, if you have some duplicated values or "holes" in that field.

Additionally you can always try to run ``./manage.py reorder <app.model>`` to restore these values.

Since I do not use Grapelli, could you please try with the standard admin theme and check if that error still occurs.

**Comment by timmyomahony** [comment] 2017-07-21 11:34
Running the management command sorted the issue for me

**Comment by jrief** [comment] 2017-07-21 11:55
would have been great to see the ordering numbers beforehand. Hmm, now it's too late.

**Comment by paddymul** [comment] 2017-07-22 16:53
Is there a command to show the ordering numbers beforehand?  I'm going to dump my database so that I can restore it after trying this command.

**Comment by paddymul** [comment] 2017-07-22 17:06
Running the reorder command did not fix this problem for me.

**Comment by jrief** [comment] 2017-07-23 16:52
@paddymul did you deactivate Grapelli?

**Comment by paddymul** [comment] 2017-07-23 18:02
I disabled grappeli and re-ran reorder and there still wasn't a proper
save. What's the easiest way to inspect the values that javascript is
sending django?  I want to narrow down whether this is a python or js
problem.

Thanks,
Paddy

**Comment by paddymul** [comment] 2017-07-23 23:22
I created a small django project that reproduces this bug for me.  it is based on https://github.com/fasouto/django-starter-template .
` $ #activate new virtualenv`
` $ pip install -r requirements.txt`
` $ python manage.py migrate`
` $ python manage.py load_sides`
` $ python manage.py createsuperuser`
` $ python manage.py runserver`
navigate to http://localhost:8000/admin/bugdemo/sidea/3/change/
and try to save a change of the ordering of ABLinks.

**Comment by enoch2110** [comment] 2017-07-25 01:41
I also experience the same problem as @paddymul does. The standard changelist_view works fine. However, the inline has the problem saving the reordered state. Even when with the reorder management command, the problem is not fixed. Also, when new objects are created after installing adminsortable2, the order field should increment on its own but the inline objects end up with 0 in the order field.

**Comment by jrief** [comment] 2017-07-25 06:56
Did you **Save** the parent object after reordering the inline fields?

**Comment by meesterguyman** [comment] 2017-07-27 17:07
I think I may have a solution for this. Problem seems to be that when an inline has fields listed, the order field is not being appended to the list, so nothing is submitted on save that would indicate a change in order. Adding the order field to the field list solves this, but this could be done programmatically as well. Submitted a pull request here.

https://github.com/jrief/django-admin-sortable2/compare/master...meesterguyman:patch-1

**Comment by jrief** [comment] 2017-07-28 10:02
what's wrong with the current workflow?

On inlines, change the order by dragging. After that save the parent object.
This works all the time and has been tested carefully.

**Comment by meesterguyman** [comment] 2017-07-28 11:58
I did not work for me. The drag and drop worked fine, but when I clicked save on anything where fields were listed, it did not save the new order. I had to add the order field to the list explicitly to make it work. But this is something that can be automated by the change I made.

**Comment by paddymul** [comment] 2017-08-10 18:55
@meesterguyman I just tested against that fix, it works for me too.   Thanks!!! @jrief can you accept the pull request and push out a new version?

**Comment by jrief** [comment] 2017-08-11 20:48
@paddymul just merged into current master. Please retest there, then I will release a new version.

**Comment by jrief** [comment] 2017-08-12 14:14
has been fixed for version 0.6.15

**Closed by jrief** 2017-08-12 14:14 UTC
