### ISSUE TITLE
Sorting not working coretcly on python36 django 1.6 (JS/CSS problem)

### ISSUE THREAD

**Issue by ManPython** [jrief/django-admin-sortable2#235] opened 2020-01-06 13:16 UTC
When moved row then I have error in browser.
```
The server responded: ValueError at /admin/test/x/adminsortable2_update/
invalid literal for int() with base 10: 'NaN'

Request Method: POST
Request URL: http://127.0.0.1:8000/admin/test/x/adminsortable2_update/
Django Version: 2.2.6
Python Executable: E:\Python36\python.exe
Python Version: 3.6.8
```
Then row looks like "colapsed" - no corect view (not justified to whole table, looks like table in cell).

In test eg. I have 2 rows. After move 1st to down, then colapsed and not visible more `my_order`, the 2nd row have this. When in this trying move 2nd row this same.. not visible more `my_order` and both rows are colapsed.

**Comment by ManPython** [comment] 2020-01-06 13:40
Repairded. It was due to that I copied `change_list.html` to `static/admin`. Strange coz I made this with isntruction for items edit.
https://django-admin-sortable2.readthedocs.io/en/latest/usage.html#overriding-change-list-page

**Comment by ManPython** [comment] 2020-01-06 13:47
Hvr.. there is some more problems.. eg. if we sorting table by `my_order ` that calling `?o=5` then no more option to drag&drop and the cells are empty. We trying refresh but `?o=5`  still exist, if we clicking more times for header of coll `my_order ` to trun off the filter the url  `?o=5` not disapering, thats mind  `my_order ` not working.

When we moving row, the d&d row is shiften little to show active row. This made that head/titles of cols are shifted and change shape that made ugly effect and "disonse shock". Soo.. active row should change colour in d&d process and should not be shifted?

**Comment by AndreyMZ** [comment] 2020-02-11 07:06
> if we sorting table by `my_order` that calling `?o=5` then no more option to drag&drop and the cells are empty. <...>

This is duplicate of bug #241.

@ManPython, please, next time create separate Github issues for separate problems.

**Closed** 2022-02-01 23:31 UTC
