### ISSUE TITLE
Django 1.7: Sortable2 1.5 TabularInline template THEAD colspan=2 broken

### ISSUE THREAD

**Issue by denhartog** [jrief/django-admin-sortable2#55] opened 2015-04-16 01:00 UTC
I upgraded Sortable2 today and now my inline admin change form is not displaying properly.

I used `collectstatic`.

I think I narrowed down the cause to the fact that `<th{% if forloop.first %} colspan="2"{% endif %}` is not being applied to my first field from the `tabular-1.5.html` template.

In a browser (Chrome; using Inspect Elements), if I add `colspan="2"` to the first (technically second after "Sort") column it displays properly.

**Comment by jrief** [comment] 2015-04-16 14:57
Sorry, I had no time yet to migrate to Django-1.7/1.8

From 1.5 to 1.6 Django changed their templates, so I also had to adopt using a modified version of it. I'm not sure if they changed again from 1.6 to 1.7.

A fixing Pull Request is welcomed.

**Comment by nicholasserra** [comment] 2015-04-16 21:19
Saw this also and ended up manually specifying the `fields` attr on the admin class.

**Comment by nicholasserra** [comment] 2015-04-16 23:50
After more digging, I realized that I had my `order` field on the model as the first editable field. Moving it to the bottom fixed my colspan issues. May still be a bug that can be fixed, but try reordering your fields.

**Comment by ddenhartog** [comment] 2015-04-17 00:36
Yeah tried using fields attr in admin with no success. You mean to say the physical order of your field definitions in your model alters the behavior of the admin template?

**Comment by nicholasserra** [comment] 2015-04-17 00:45
Yes, exactly. The admin fields are ordered based on the field order in the Model. So rearranging them worked for me. 

Also, I implemented the Django 1.7 templates with no success. I didn't see any major changes that should affect this.

**Comment by ddenhartog** [comment] 2015-04-23 03:47
@nicholasserra,

Reordering the sort field (I defined mine last) solves the colspan issue. Clearly a bug, but I couldn't quickly identify the cause and am back focused on my project; I'll let @jrief focus on his *cough* sortable2 *cough* :D

**Comment by rubengrill** [comment] 2016-06-10 10:26
Still an issue in Django 1.9, fixed in #107.

**Comment by jrief** [comment] 2016-06-11 14:05
closed via #107

**Closed by jrief** 2016-06-11 14:05 UTC
